version: '3.3'
services:
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - '3306:3306'
    expose:
      - '3306'
      
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
